import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { getPokemon, getPokemonInterval } from "./api/endpoints";
import styles from "../styles/styles.module.css";

interface pokemon {
  name: string;
  url: string;
}

interface onePokemon {
  name: string;
  img: string;
}

const Home: NextPage = () => {
  const [listPokemon, setListPokemon] = useState([]);
  const [onePokemon, setOnePokemon] = useState<onePokemon>({
    name: "",
    img: "",
  });
  const [openPokemon, setOpenPokemon] = useState(false);
  useEffect(() => {
    getPokemonInterval(0, 151, setListPokemon);
  }, []);

  return (
    <div className={styles.prince}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1> POKEMON</h1>
      </div>
      <div className={styles.in}>
        {!openPokemon &&
          listPokemon?.map((value: any) => (
            <div key={value?.name}>
              <button
                onClick={() => {
                  getPokemon(value?.name, setOnePokemon);
                  setOpenPokemon(!openPokemon);
                }}
              >
                {value?.name}
              </button>
            </div>
          ))}
      </div>
      {openPokemon && (
        <div className={styles.poke}>
          <div className={styles.imagem}>
            <img src={onePokemon?.img} alt="foto" />
            <h2>{onePokemon?.name}</h2>
          </div>
          <div className={styles.volta}>
            <button
              onClick={() => {
                setOpenPokemon(!openPokemon);
              }}
            >
              voltar
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Home;
